### ISSUE TITLE
A little information on how to improve custom embed builder

### ISSUE THREAD

**Issue by StrangeEcho** [cheekysim/Williepillar#4]
I havent theoretically tested this but this could possibly make the code be neater and more efficient. Instead of normally indexing you can use `.get` because it seems you're using the try/excepts for if the person building the embed doesnt pass in a specific value. An example in what I mean:
```py
embed.set_author(name=field.get("name", embed.Empty), url=field.get("url", embed.Empty), icon_url=field.get("icon", embed.Empty))
```
similar to how you were handling it before.

**Comment by cheekysim** [comment]
It works!
